// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5G_ntdRofLq_LT8zMiLAazcoAH2pZKEg',
    appId: '1:735878764760:web:5a303c2cfd2161f89d1fad',
    messagingSenderId: '735878764760',
    projectId: 'clovi-17ec1',
    authDomain: 'clovi-17ec1.firebaseapp.com',
    storageBucket: 'clovi-17ec1.firebasestorage.app',
    measurementId: 'G-B462EZ6C7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPGnbjNGlvczQMlgV9OTRC0MmrXSqJ5xE',
    appId: '1:735878764760:android:a65ec6a7fcdd49549d1fad',
    messagingSenderId: '735878764760',
    projectId: 'clovi-17ec1',
    storageBucket: 'clovi-17ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu-XPNbe_f8DdG2fDos-39cUf1QABQ46o',
    appId: '1:735878764760:ios:a4f8673feb31dea09d1fad',
    messagingSenderId: '735878764760',
    projectId: 'clovi-17ec1',
    storageBucket: 'clovi-17ec1.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu-XPNbe_f8DdG2fDos-39cUf1QABQ46o',
    appId: '1:735878764760:ios:a4f8673feb31dea09d1fad',
    messagingSenderId: '735878764760',
    projectId: 'clovi-17ec1',
    storageBucket: 'clovi-17ec1.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5G_ntdRofLq_LT8zMiLAazcoAH2pZKEg',
    appId: '1:735878764760:web:578d94582d0407c09d1fad',
    messagingSenderId: '735878764760',
    projectId: 'clovi-17ec1',
    authDomain: 'clovi-17ec1.firebaseapp.com',
    storageBucket: 'clovi-17ec1.firebasestorage.app',
    measurementId: 'G-5JR90K1N1T',
  );
}
